### PR TITLE
Container orchestration

### PR DESCRIPTION
**Pull request by RajendraBhagroo**
Team,

Please refer to the new documentation (README) as I have refactored the config/ directory to no longer use javascript files. We now use .env files and you will need to set yours up! 

I will work on integrating docker-compose so we can deploy our application.

### CODE REVIEW

**Review by Gold-Turtle — DISMISSED** [review]
Approved

**Review by gint0kix — DISMISSED** [review]
Approved

**Comment by RajendraBhagroo** [comment]
Team,

The projects root Dockerfile is now segmented across [server/] and [client/] directories. I implemented docker-compose.yml to orchestrate the dockerfiles in the server and client so it is very easy to build our containers, run them, and teardown our containers.

Kubernetes is overkill for our project 👎  I really wanted to get some hands-on experience with that.

The dev files for Docker have "-dev" specified in the file names. The production files (which do not yet work) exist in our project for further completion when we are finished with our project.

**Review by Gold-Turtle — APPROVED** [review]
Approved

**Review by gint0kix — APPROVED** [review]
approved

**Pull request merged**
