### PR TITLE
Landing Page

### PR DESCRIPTION
**Pull request by Gold-Turtle**
Finish added landing page, but need to add something on the bottom.

### CODE REVIEW

**Comment by RajendraBhagroo** [comment]
Css Was Globally Scoped Due To React And SPA Loading. Kim and I Fixed That Issue.

**Review by RajendraBhagroo — DISMISSED** [review]

**Review by gint0kix — DISMISSED** [review]
Approved

**Review by RajendraBhagroo — APPROVED** [review]

**Comment by RajendraBhagroo** [comment]
@gint0kix 

Please review the change I introduced into Stream.js. There was a merge conflict and I accepted the incoming change, as the old code was refactored into two seperate files.

**Review by gint0kix — APPROVED** [review]
Stream page looks good

**Pull request merged**
