### PR TITLE
Server setup

### PR DESCRIPTION
**Pull request by RajendraBhagroo**
Team,

I Refactored Server Code Into Its Own Folder For Clarity. Setup Scripts. Updated README.

### CODE REVIEW

**Comment by RajendraBhagroo** [comment]
Sorry About closing this branch and forcing pushes and re-opening it. You should NEVER do that! I had to wipe my computer and lost my GPG key, therefore the required verification check on any commit would have kicked in on the master branch and rejected these changes on merge.

**Review by gint0kix — DISMISSED** [review]
Approved

**Review by Gold-Turtle — DISMISSED** [review]
Approved

**Review by Gold-Turtle — APPROVED** [review]
Change approved

**Pull request merged**
