### PR TITLE
Profile Routes

### PR DESCRIPTION
**Pull request by Gold-Turtle**
I made profile update form on new file call ProfileUpdateTest.js, because I couldn't open Profile.js on profile folder when I run the program. I tried to add checkbox that opens another input box. I didn't put all input boxes like "school name, years, etc.." Also I didn't solve one problem situation that when user try to put both check boxes at the same time. I saw we can control it with JQuery or other things but I'm not sure we can use it or not in this project. So this is just draft.

### CODE REVIEW

**Comment by RajendraBhagroo** [comment]
I'll take a look in the morning. Goodnight Kim!

**Comment by RajendraBhagroo** [comment]
Goodmorning Kim, looks good. Run [npm uninstall --save classnames] in the root folder. This dependancy already exists in [client/] and in the root it has no code to touch. 

Keep working on the button and add more commits, so far looks good !

**Comment by RajendraBhagroo** [comment]
@Gold-Turtle ,

I am REALLY impressed by your work Kim!

We just need to continue working on Redux & implementing functionality on the client to interact with the corresponding back-end routes. profile handle is something I have to look into. PropTypes, isStudent checkbox to state, and other things need to be addressed before merging.

Be sure to tag me in discord and share your screen w/me if you run into problems, I am always here to help.

One step closer, and again ... thank you for the hardwork Kim!

**Comment by RajendraBhagroo** [comment]
@Gold-Turtle ,

Replicate same functionality for education and experience creating their own respective actions in Redux for each view, just like how we did for creating a profile.

To delete education and experience we will have to do so through their unique Id's on the profile itself, which means we will create logic to retrieve the profile and validate that the user viewing the profile is the profile owner. We can discuss this after adding education and experience works. To finish up this pull request we will need to implement updating the profile and displaying the public profile and correcting small things such as private/public routes.

**Comment by RajendraBhagroo** [comment]
@Gold-Turtle ,

See [Profile Route Fixes] In Your Card At [Our Github Project Board](https://github.com/RajendraBhagroo/TeleQuest/projects/1)

I made some changes, be careful when copying and pasting Kim!, carefully review your files. I also added the functionality of getting the user profile from our database so you can change the hardcoded values in the main profile display to the ones in the database. I made a profile variable, you will see it. Also, use Redux devtools to see the profile as well, under "state".

Make sure before you change any files, Git pull origin [Your Branch Name]

I made changes so you need to pull before you start working again

**Comment by RajendraBhagroo** [comment]
@Gold-Turtle ,

As a reminder, we need to implement functionality to allow the profile to transition into a loading state while the action fetches info from our database. You will need a spinner, and to edit profileActions and profileReducer.

Also, for each field in the profile that is enumerable, [education,experience, coursesEnrolledIn, coursesTeaching] you can refactor the code to display each discrete segment of info into its own component and loop over the component using a Javascript expression.

After that, just check your board in the TeleQuest main projec board and ensure your card has no Todo's and the profile stuff is done!


@gint0kix , meanwhile, you can create a "streams" tab in the navbar and work on getting the streaming routes up and going, the only segment of info you needed from the profile is "isStudent" and its good to go in the application level state.

**Comment by RajendraBhagroo** [comment]
@Gold-Turtle  , 

Please push your latest code so I can take a crack at the profile loading aspect we spoke about yesterday.

**Comment by RajendraBhagroo** [comment]
image

@Gold-Turtle , you forgot to keep track of profile loading status in application level state. The reason loading does not work is because our application has no idea if the profile is loading or not. It will check the profileReducer for the boolean loading status.

**Comment by RajendraBhagroo** [comment]
@Gold-Turtle  ,

The spinner & profile loading state is properly implemented and functional!

I have created empty files [ShowEducation & ShowExperience]. Please refactor profile.js file and seperate each section into its own component.

Also, we will need to implement two more sections to be included on profile.js, those are [coursesEnrolledIn and coursesTeaching]. Both sections will need their own form component and display component that al link back to profile.js.

After that, profile.js is good to go and we need to tackle the next portion of our application, live-streaming!

** Make sure you [git pull origin branchname] before you begin working so you have my latest remote changes on your local branch. And keep up the good work KIm!

**Comment by RajendraBhagroo** [comment]
Hardwork and long hours Kim!

I'm very impressed with your creativity when it comes to designing the profile and the discipline you have to put in work and even wait for me to be available to help when needed. Get some sleep, we will pickup on this tomorrow.

**Comment by RajendraBhagroo** [comment]
@Gold-Turtle @gint0kix ,

Chris, please review this code and approve so we can finally merge the profile changes! I am so excited, Kim you did an amazing job. Now we move onto streams!

**Review by RajendraBhagroo — APPROVED** [review]

**Review by gint0kix — APPROVED** [review]
Approved

**Pull request merged**
