### PR TITLE
Code Refactor - Profile Model

### PR DESCRIPTION
**Pull request by RajendraBhagroo**
Major Refactor. Instead of replicating [v1] everywhere I realized that developers can update the server in source control, but the moment they edit/add a model, they will need to edit/add functionality to routes,tests & validation, therefore breaking existing functionality and moving to a new version. This does not really affect us on the small scale, but as an engineer you should ALWAYS think ahead and what is appropriate for the software development lifecycle & scope.

Also, I revamped the Profile Model. @gint0kix @Gold-Turtle  we should discuss that as a team to move forward.

User profiles can be publicly accessed. I believe that our plan of conditionally showing/hiding profile fields in the front-end will cause a problem because of the required fields in the Profile Model file in the backend. Example, If you look at the profile model you will see [studentFields, teacherFields] each of which has requirements on data that MUST be filled out. You will notice that both fields live inside one model. If we hide either fieldGroup on the front-end, we are still creating an instance of profile model that contains both groups. One group will always have a requirement that MAY cause the save to fail.

We should test on postman to see if excluding a fieldgroup in profile creation will give an error, If it does I recommend either removing the required fields on the field groups entirely and moving those requirements into the validation files, or using Mongoose discriminators. I looked into Mongoose discriminators and it seems like it wouldn't be a good idea because of the logic that a user can become a teacher, or a teacher can become a student.

If we save a profile as a student and they become a teacher, I wouldn't know how to convert their profile from one discriminator to another since you save them separately. Although, A good idea is to still keep the logic in one profile, remove requirements on the model and enforce them in the validation to preserve data consistency (which is what the validation files are supposed to do in the first place). This way, we are able to keep one profile model and still have enforcements within a noSQL or SQL database via validation files. The model (Schema & Tables) can focus on what data is going to be stored and retrieved & the validation files can focus on how the data going in is structured. Seems weird since every DB lets you describe requirements on data but we are just delegating the job to keep strict standards but maintain the flexibility of one profile.

### CODE REVIEW

**Comment by RajendraBhagroo** [comment]
@gint0kix @Gold-Turtle  Minor Change In Your [.env] File. Change ROUTE_VERSION to SERVER_VERSION. We should also discuss the project as a team as soon as you can over discord

**Review by gint0kix — DISMISSED** [review]
Approved

**Comment by RajendraBhagroo** [comment]
Team,

Literally 12 hours of coding to get the job done. I know I was ambitious for the profile routes but this is senior project, go big or go home. I wanted something not over the top, but nice and I'm happy to say that the profile routes are good to go.

See commit messages, there is alot that needs to be improved with route validation & unit testing. I will hop on that another day.

**Review by Gold-Turtle — APPROVED** [review]
Approved

**Review by gint0kix — APPROVED** [review]
Approved

**Pull request merged**
